
GET http://localhost:5000/

###

GET http://localhost:5000/6550cf4d94d99cc251fb2707
###
POST http://localhost:5000/
Content-Type: application/json

{
    "title": "Microsoft Surface Laptop ",
    "description": "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen",
    "price": "1499",
    "brand": "Microsoft Surface",
    "category": "laptops",
    "images": "https://i.dummyjson.com/data/products/8/1.jpg",
    "thumbnail": "https://i.dummyjson.com/data/products/8/thumbnail.jpg"
    
}

###
https://dummyjson.com/products

