
GET http://localhost:5000/

###

GET http://localhost:5000/6550cf4d94d99cc251fb2707
###
POST http://localhost:5000/
Content-Type: application/json

{
    "title": "Samsung Universe 9",
    "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
    "price": "1249",
    "brand": "Samsung",
    "category": "smartphones",
    "images": "https://i.dummyjson.com/data/products/3/1.jpg",
    "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg"
    
}

