
GET http://localhost:5000/

###

GET http://localhost:5000/6551bf269b9d167d00dc42ec
###
POST http://localhost:5000/
Content-Type: application/json

{
    "title": "perfume Oil ",
    "description": "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
    "price": "13",
    "brand": "Impression of Acqua Di Gio",
    "category": "fragrances",
    "images": "https://i.dummyjson.com/data/products/11/1.jpg",
    "thumbnail": "https://i.dummyjson.com/data/products/11/thumbnail.jpg"
    
}

###
https://dummyjson.com/products

